-- Basic Database Model

CREATE TABLE users(id SERIAL PRIMARY KEY, username TEXT NOT NULL, email TEXT NOT NULL, psd TEXT NOT NULL, pic TEXT DEFAULT 'default.jpg');

CREATE TABLE books(id INTEGER PRIMARY KEY, isbn TEXT NOT NULL, title TEXT NOT NULL, author TEXT NOT NULL, year, INTEGER NOT NULL, );

CREATE TABLE reviews(id INTEGER PRIMARY KEY, userID TEXT NOT NULL, bookID TEXT NOT NULL, rating TEXT NOT NULL, FOREIGN KEY(userID) REFERENCES users, FOREIGN Key(bookID), REFERENCES books, );
